[book]
authors = ["Jack Darlison"]
language = "en"
multilingual = false
src = "src"
title = "The Little Book of NLP"

[build]
build-dir = "docs"
create-missing = true

[output.html]
mathjax-support = true
